name: Run JMeter Performance Test

on:
  workflow_dispatch:
    inputs:
      jmx_file:
        description: 'The JMeter .jmx file to run'
        required: true
        type: choice
        options:
          - jmeter-scripts/LoadTesting.jmx
        default: 'jmeter-scripts/performance-test.jmx'

jobs:
  run_jmeter_test:
    name: Run JMeter Test for ${{ inputs.jmx_file }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Extract the base name of the .jmx file
      - name: Get JMX file name
        id: jmx_name
        run: |
          jmx_path_and_name="${{ inputs.jmx_file }}"
          jmx_filename="${jmx_path_and_name##*/}"
          jmx_basename="${jmx_filename%.jmx}"
          echo "JMX_BASENAME=$jmx_basename" >> $GITHUB_ENV

      # Step 4: Install JMeter Plugins
      # This step installs the plugins into the Docker image's JMeter libraries.
      - name: Install JMeter Plugins for Ultimate Thread Group
        run: |
          # Use a specific version of the JMeter image for consistency, or 'latest'
          JMETER_IMAGE_NAME="justb4/jmeter:latest"

          # Use a Docker container to install the plugins
          # The plugins will be installed into a volume that persists for the test run
          docker run --rm \
            -v ${{ github.workspace }}/jmeter-scripts/plugins:/plugins \
            -v ${{ github.workspace }}:/jmeter/workspace \
            -v ${{ github.workspace }}/jmeter-results:/jmeter/results \
            -w /jmeter \
            "${JMETER_IMAGE_NAME}" \
            /bin/bash -c " \
              # Download Plugins Manager (if not already there) \
              if [ ! -f /jmeter/lib/ext/jmeter-plugins-manager.jar ]; then \
                curl -L --silent https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/2.10/jmeter-plugins-manager-2.10.jar -o /jmeter/lib/ext/jmeter-plugins-manager.jar; \
              fi; \
              # Install the required plugins using the Plugins Manager CLI \
              /jmeter/lib/ext/plugins-manager.jar install jpgc-casutg jpgc-standard"

      # Step 5: Generate a dynamic timestamp
      - name: Set dynamic timestamp
        id: timestamp_step
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      # Step 6: Run the JMeter test with Docker
      - name: Run JMeter test with dynamic filenames
        run: |
          JMETER_IMAGE_NAME="justb4/jmeter:latest"
          docker run --rm \
            -v ${{ github.workspace }}/jmeter-scripts/plugins:/jmeter/lib/ext \
            -v ${{ github.workspace }}:/jmeter/workspace \
            -v ${{ github.workspace }}/jmeter-results:/jmeter/results \
            -w /jmeter/workspace \
            "${JMETER_IMAGE_NAME}" \
            -n -t "${{ inputs.jmx_file }}" \
            -l "/jmeter/results/report-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}.jtl" \
            -e -o "/jmeter/results/jmeter-report-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}"

      # Steps 7 and 8 remain unchanged and will upload the artifacts.
      - name: Upload JMeter Results File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}
          path: jmeter-results/report-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}.jtl

      - name: Upload JMeter HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}
          path: jmeter-results/jmeter-report-${{ env.JMX_BASENAME }}-${{ env.TIMESTAMP }}/
