name: JMeter Performance Tests

on:
  workflow_dispatch:
    inputs:
      jmxFile:
        description: 'The JMeter .jmx file to run'
        required: true
        type: choice
        options:
          - jmeter-scripts/LoadTesting.jmx
        default: 'jmeter-scripts/LoadTesting.jmx'

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Dynamic Filename
        id: prep
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          FILENAME=$(basename "${{ inputs.jmxFile }}" .jmx)
          REPORT_NAME="${FILENAME}-${TIMESTAMP}"
          echo "REPORT_NAME=${REPORT_NAME}" >> "$GITHUB_ENV"

      - name: Run JMeter Tests and Generate HTML Report
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ${{ inputs.jmxFile }}
          outputReportsFolder: reports/
          args: >
            -e -o reports/${{ env.REPORT_NAME }}_dashboard
            --loglevel INFO 
            -JMyProperty=Value
            --jmeterlogconf=log.conf
          plugins: "jpgc-casutg"

      - name: Upload JMeter JTL Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-jtl-report
          path: reports/${{ env.REPORT_NAME }}.jtl
          
      - name: Upload JMeter HTML Dashboard
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-dashboard
          path: reports/${{ env.REPORT_NAME }}_dashboard/
